### ISSUE TITLE
COUNT summary is incorrect

### ISSUE THREAD

**Issue by kanitw** [uwdata/polestar#259]
movie says only have 400 rows, which is wrong

**Comment by kanitw** [comment]
This is probably due to the bad popup plugins that renders once.

**Comment by domoritz** [comment]
I'll fix it today.

**Comment by domoritz** [comment]
Will be solved by https://github.com/720kb/angular-tooltips/pull/24

**Comment by kanitw** [comment]
Somehow it seems to behave correctly already  as of 
https://github.com/uwdata/polestar/commit/6d071b4f849d7ab011368135af24bd27ca4c4307

So I’m closing this.
