### ISSUE TITLE
Data Paste

### ISSUE THREAD

**Issue by kanitw** [uwdata/polestar#279]
- [ ] fix `.data()` bug in vega
- [ ] create UI control
- [ ] update dataset.js
- [ ] update vlplot.js

**Comment by domoritz** [comment]
Issue in vl https://github.com/uwdata/vegalite/issues/424

**Comment by kanitw** [comment]
They are not exactly the same thing.  Let's discuss this afterward

**Comment by kanitw** [comment]
done?
