### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by naehrstoff** [uwdata/polestar#286]
I followed the instructions outlined in the readme to build this project and serve locally, but wasn't able to get Polestar to build correctly. Angular complains that `vlui` is missing:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module polestar due to:
Error: [$injector:modulerr] Failed to instantiate module vlui due to:
Error: [$injector:nomod] Module 'vlui' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.3.15/$injector/nomod?p0=vlui
```

I then tried to build vega-lite (which I cloned as per the instructions to be next to the polestar folder) and wasn't able to build that project either (`Error: Cannot find module 'datalib/src/bin'`).

Now I'm a bit at a loss on where to start trying to fix things …

The reason I actually tried to build the project was to provide my class with access to Polestar for a custom dataset (for which the import through the demo application doesn't work for some reason – not as a hosted file, not as pasted CSV). So if this build issue is hard to fix, could you maybe recommend a combination of versions of these libraries that works well to build and that I could use?

In case you can't reproduce this build problem in a fresh install, I'll be happy to provide any log files needed. Thanks!

**Comment by kanitw** [comment]
Hi, 

Thanks for reaching out.  I have just done some refactoring last week and probably introduced these errors by mistake.  I will try to take a look at these sunday night or monday and let you know!\

–Kanit

**Comment by kanitw** [comment]
I've updated some dependencies in bower.json.  If you pull and run `bower install` again, polestar should work now.  

I also updated the readme and remove the need to clone vega-life into the same folder.  

Please let me know if you still run into problem.

**Comment by naehrstoff** [comment]
Thanks a lot! Works as expected now and I was able to achieve what I needed :+1:

I also like that the setup with the `_visrec` folder is no longer necessary.

**Comment by kanitw** [comment]
@naehrstoff  You're welcome!    By the way,  I'm just wonder what class are you using polestar for? :)

**Comment by naehrstoff** [comment]
We're doing a workshop for journalists and Polestar is perfect to quickly get some insights into the dataset and process of looking at a dataset from different angles. I'll also show some other tools from the Vega suite :)

**Comment by domoritz** [comment]
@naehrstoff That's awesome. Let us know if there is anything we can help with!
