### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by domoritz** [uwdata/polestar#289]
Reported by @jheer 

Unfortunately, the online demo is currently broken :(

Specifically, it looks like binning does not work. Try this shorthand:
mark=point|x=bin_Horse_Power,Q|y=bin_Miles_per_Gallon,Q|size=count_*,Q

I get a plot with no data points in it.

**Comment by domoritz** [comment]
It looks like binning horse power doesn't work at all. The following spec works in the vl editor but looks broken:

```
{
  "marktype": "point",
  "enc": {
    "y": {"type": "Q","name": "Horse_Power", "bin": {"maxbins": 15}},
    "x": {"type": "Q","name": "*","aggr": "count"}
  },
  "data": {"url": "data/cars.json"}
}
```

![screen shot 2015-05-20 at 23 14 54](https://cloud.githubusercontent.com/assets/589034/7742616/1564c850-ff46-11e4-813e-716b5fcc6e32.png)

I can't get polestar to work right now because of some CSS issues probably caused by the slit of polestar and vl-ui.

**Comment by kanitw** [comment]
@jheer  @domoritz 

I tried the same thing locally with both `gulp serve` and `gulp serve:dist` and it works properly.  

So there must be something wrong with the publish script.  I’m investigating this now.
