### ISSUE TITLE
Legend for shape is not visible with color and size

### ISSUE THREAD

**Issue by vivekratnavel** [uwdata/polestar#305]
Cannot see all the three legends for the following spec.

```
{
  "marktype": "point",
  "encoding": {
    "x": {"name": "Origin","type": "O"},
    "y": {"name": "Cylinders","type": "O"},
    "size": {"name": "Displacement","type": "Q"},
    "color": {"name": "Horsepower","type": "Q"},
    "shape": {"bin": {"maxbins": 15},"name": "Miles_per_Gallon","type": "Q"}
  },
  "config": {"singleHeight": 400,"singleWidth": 400,"largeBandMaxCardinality": 20},
  "data": {"url": "data/cars.json"}
}
```

Removing either of the color or size brings up legend for shape.

**Comment by kanitw** [comment]
Thanks for reporting issues. 

This is actually a vega-life issue.  Also, it is redundant with https://github.com/uwdata/vega-lite/issues/131 so I'm closing this for now.  #131 is in the roadmap and will be fixed once we migrate to vega2.
